<<: &shared
  language_name: nsyilxən
mappings:
  - display_name: nsyilxən to IPA
    in_lang: nsyilxən
    out_lang: nsyilxən-ipa
    authors:
      - Craig Carpenter
    type: mapping
    mapping: nsyilxən_to_ipa.csv
    in_lang: nsyilxən-ipa
    out_lang: nsyilxən-arpabet
    authors:
      - Craig Carpenter
    type: mapping
    mapping: nsyilxən_ipa_arpabet.csv